# Generated by Django 3.2.8 on 2021-11-15 09:19

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('api', '0003_createuserdraft'),
    ]

    operations = [
        migrations.DeleteModel(
            name='CreateUserDraft',
        ),
    ]
