# Generated by Django 3.2.8 on 2021-12-13 18:56

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('api', '0004_delete_createuserdraft'),
    ]

    operations = [
        migrations.AlterModelOptions(
            name='product',
            options={'ordering': ('-created_at', 'variants__quantity')},
        ),
        migrations.AlterModelOptions(
            name='productvariant',
            options={'ordering': ['price', '-discount']},
        ),
        migrations.AddField(
            model_name='product',
            name='variable_price',
            field=models.BooleanField(default=False),
        ),
    ]
