# Generated by Django 3.2.8 on 2021-12-13 19:47

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('api', '0007_auto_20211213_2311'),
    ]

    operations = [
        migrations.AddField(
            model_name='productvariant',
            name='variable_price',
            field=models.BooleanField(default=False),
        ),
    ]
