# Generated by Django 3.2.8 on 2021-12-13 21:24

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('api', '0008_productvariant_variable_price'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='productvariant',
            name='variable_price',
        ),
    ]
