# Generated by Django 3.2.8 on 2021-10-18 07:41

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('api', '0009_rename_likes_like'),
    ]

    operations = [
        migrations.AlterField(
            model_name='product',
            name='gallery',
            field=models.ManyToManyField(blank=True, null=True, to='api.GalleryImage'),
        ),
    ]
