# Generated by Django 3.2.8 on 2021-10-18 07:42

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('api', '0010_alter_product_gallery'),
    ]

    operations = [
        migrations.AlterField(
            model_name='product',
            name='gallery',
            field=models.ManyToManyField(to='api.GalleryImage'),
        ),
    ]
