# Generated by Django 3.2.8 on 2021-10-18 08:12

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('api', '0011_alter_product_gallery'),
    ]

    operations = [
        migrations.AddField(
            model_name='like',
            name='deleted_at',
            field=models.DateTimeField(blank=True, null=True),
        ),
    ]
