# Generated by Django 3.2.8 on 2021-10-19 13:27

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('api', '0015_address'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='address',
            name='country',
        ),
    ]
