# Generated by Django 3.2.8 on 2021-10-20 12:45

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('api', '0018_banner_slider'),
    ]

    operations = [
        migrations.AddField(
            model_name='order',
            name='payment_succeed',
            field=models.BooleanField(default=False),
        ),
    ]
