# Generated by Django 3.2.8 on 2021-10-22 12:58

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('api', '0023_order_address'),
    ]

    operations = [
        migrations.AddField(
            model_name='address',
            name='city_code',
            field=models.CharField(default=32, max_length=10),
            preserve_default=False,
        ),
        migrations.AddField(
            model_name='address',
            name='state_code',
            field=models.CharField(default=54, max_length=10),
            preserve_default=False,
        ),
        migrations.AlterField(
            model_name='orderitem',
            name='order',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='order_items', to='api.order'),
        ),
    ]
