# Generated by Django 3.2.8 on 2021-10-22 13:20

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('api', '0026_alter_order_address'),
    ]

    operations = [
        migrations.AddField(
            model_name='product',
            name='weight',
            field=models.IntegerField(default=200),
            preserve_default=False,
        ),
    ]
