# Generated by Django 3.2.8 on 2021-10-22 16:46

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('api', '0027_product_weight'),
    ]

    operations = [
        migrations.AddField(
            model_name='product',
            name='description',
            field=models.TextField(blank=True, null=True),
        ),
        migrations.AddField(
            model_name='product',
            name='details',
            field=models.TextField(blank=True, null=True),
        ),
    ]
