# Generated by Django 3.2.8 on 2021-10-22 16:50

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('api', '0028_auto_20211022_2016'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='product',
            name='delivery_mode',
        ),
    ]
