# Generated by Django 3.2.8 on 2021-10-23 12:18

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('api', '0030_auto_20211023_1547'),
    ]

    operations = [
        migrations.AddField(
            model_name='order',
            name='pay_url',
            field=models.URLField(blank=True, null=True),
        ),
    ]
