# Generated by Django 3.2.8 on 2021-10-23 13:05

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('api', '0032_order_canceled'),
    ]

    operations = [
        migrations.RenameField(
            model_name='order',
            old_name='discount',
            new_name='amount',
        ),
        migrations.RenameField(
            model_name='order',
            old_name='price',
            new_name='discount_amount',
        ),
    ]
