# Generated by Django 3.2.8 on 2021-10-23 13:24

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('api', '0034_order_ref_id'),
    ]

    operations = [
        migrations.AddField(
            model_name='order',
            name='checkout_datetime',
            field=models.DateTimeField(blank=True, null=True),
        ),
        migrations.AddField(
            model_name='order',
            name='success_payment_datetime',
            field=models.DateTimeField(blank=True, null=True),
        ),
    ]
