# Generated by Django 3.2.8 on 2021-10-29 18:42

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('api', '0038_alter_slider_url'),
    ]

    operations = [
        migrations.AlterField(
            model_name='banner',
            name='url',
            field=models.CharField(max_length=200),
        ),
    ]
