# Generated by Django 3.2.8 on 2021-10-30 08:18

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('api', '0040_auto_20211030_1145'),
    ]

    operations = [
        migrations.AddField(
            model_name='country',
            name='slug',
            field=models.CharField(default='dsf', max_length=20),
            preserve_default=False,
        ),
    ]
