# Generated by Django 3.2.8 on 2021-10-31 09:48

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('api', '0041_country_slug'),
    ]

    operations = [
        migrations.AlterField(
            model_name='category',
            name='show_in_home',
            field=models.BooleanField(default=False),
        ),
    ]
