# Generated by Django 3.2.8 on 2021-10-31 10:41

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('api', '0042_alter_category_show_in_home'),
    ]

    operations = [
        migrations.AddField(
            model_name='address',
            name='house_number',
            field=models.IntegerField(blank=True, null=True),
        ),
        migrations.AddField(
            model_name='address',
            name='unit',
            field=models.IntegerField(blank=True, null=True),
        ),
    ]
