# Generated by Django 3.2.8 on 2021-10-31 11:21

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('api', '0043_auto_20211031_1411'),
    ]

    operations = [
        migrations.RenameField(
            model_name='address',
            old_name='person_name',
            new_name='fist_name',
        ),
        migrations.AddField(
            model_name='address',
            name='last_name',
            field=models.CharField(blank=True, max_length=100, null=True),
        ),
    ]
