# Generated by Django 3.2.8 on 2021-10-31 12:56

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('api', '0044_auto_20211031_1451'),
    ]

    operations = [
        migrations.AddField(
            model_name='address',
            name='zip_code',
            field=models.IntegerField(default=33),
            preserve_default=False,
        ),
    ]
