# Generated by Django 3.2.8 on 2021-11-01 05:03

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('api', '0046_alter_address_user'),
    ]

    operations = [
        migrations.AddField(
            model_name='order',
            name='Warehouse_confirmation',
            field=models.BooleanField(default=False),
        ),
    ]
