# Generated by Django 3.2.8 on 2021-11-01 05:14

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('api', '0047_order_warehouse_confirmation'),
    ]

    operations = [
        migrations.RenameField(
            model_name='address',
            old_name='fist_name',
            new_name='first_name',
        ),
    ]
