# Generated by Django 3.2.8 on 2021-11-01 14:09

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('api', '0050_order_returned'),
    ]

    operations = [
        migrations.RenameField(
            model_name='order',
            old_name='Warehouse_confirmation',
            new_name='warehouse_confirmation',
        ),
    ]
