# Generated by Django 3.2.8 on 2021-11-02 21:50

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('api', '0054_auto_20211103_0112'),
    ]

    operations = [
        migrations.AddField(
            model_name='color',
            name='slug',
            field=models.CharField(default='sample', max_length=50),
            preserve_default=False,
        ),
        migrations.AlterField(
            model_name='color',
            name='name',
            field=models.CharField(max_length=50),
        ),
    ]
