# Generated by Django 3.2.8 on 2021-11-14 13:37

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('user', '0004_registerdraft'),
    ]

    operations = [
        migrations.DeleteModel(
            name='RegisterDraft',
        ),
    ]
