# Generated by Django 3.2.8 on 2021-11-14 13:37

import django.core.validators
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('user', '0005_delete_registerdraft'),
    ]

    operations = [
        migrations.CreateModel(
            name='RegisterDraft',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('phone_number', models.CharField(max_length=17, unique=True, validators=[django.core.validators.RegexValidator(message='enter valid phone number', regex='^\\+?1?\\d{9,15}$')])),
                ('user_data', models.JSONField()),
                ('code', models.CharField(max_length=10)),
                ('generate_at', models.DateTimeField(auto_now=True)),
            ],
        ),
    ]
