# Generated by Django 3.2.8 on 2021-11-15 09:26

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('user', '0008_registerdraft_registered'),
    ]

    operations = [
        migrations.RenameField(
            model_name='registerdraft',
            old_name='user_data',
            new_name='data',
        ),
    ]
