# Generated by Django 3.2.8 on 2021-11-15 09:41

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('user', '0010_rename_data_registerdraft_form'),
    ]

    operations = [
        migrations.RenameField(
            model_name='registerdraft',
            old_name='generate_at',
            new_name='started_at',
        ),
    ]
